# Generated by Django 5.1.7 on 2025-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_generado_por_alter_reporte_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('financiero', 'Financiero'), ('inventario', 'Inventario'), ('pedidos', 'Pedidos'), ('proveedores', 'Proveedores')], max_length=50),
        ),
    ]
